language: php
php: "7.1"
env:
   global:
      setup:basic
      APP_ENV:local
      APP_DEBUG:true
      APP_KEY:IgxC8XrTr7zAr1lVffgiMZ5gUXsBaJyQZyagdqnKwhY=
      DB_CONNECTION:mysql
      CACHE_DRIVER:file
      SESSION_DRIVER:file
      QUEUE_DRIVER:sync

sudo: "false"
script: vendor/bin/phpunit	